image: registry.gitlab.com/everythingfunctional/dockerfpm

test:
  script:
    - fpm test # TODO: run with valgrind once gfortran memory leaks have been fixed, i.e.  --runner "valgrind --leak-check=full --error-exitcode=1"
